# ======================================================================
# Makefile 
# for make-chicken-units
# ======================================================================
#

include ../mk/chicken-config.mk

SOURCES = make-chicken-units.scm application.scm 
EXE = make-chicken-units

include ../mk/chicken-appmaker.mk
