# ======================================================================
# Makefile 
# for tst-sl-printf
# ======================================================================
#

SOURCES = println.scm slprintf.scm 
MAIN = tst-sl-printf.scm
EXE = tst-sl-printf

include ../mk/chicken-r7rs-config.mk
