# ======================================================================
# Makefile 
# for tst-sl-printf
# ======================================================================
#

SOURCES = println.scm slprintf.scm 
MAIN = test.scm
EXE = test
CSCFLAGS = -I../match -rpath ../match

include ../mk/chicken-r7rs.mk
