# ======================================================================
# Makefile 
# for tester
# ======================================================================
#

SOURCES = tester.scm
MAIN = test.scm
EXE = test
CSCFLAGS = -include-path ../sl-printf

include ../mk/chicken-r7rs.mk
