# ======================================================================
# Makefile 
# for test
# ======================================================================
#

SOURCES = bbmatch.scm
MAIN = test.scm
EXE = test
CSCFLAGS = -I ../../sl-printf -R chicken-syntax

include ../../mk/chicken-r7rs.mk
