# ======================================================================
# Makefile 
# for test
# ======================================================================
#

SOURCES = bbmatch.scm
MAIN = test.scm
EXE = test
CSCFLAGS = -include-path ../sl-printf -include-path ../tester -R chicken-syntax

include ../mk/chicken-r7rs.mk
